import { ArrowRight, Clock3, MapPin, Navigation, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import PageMeta from "@/components/PageMeta";
import SiteShell from "@/components/SiteShell";
import { defaultVendors, publishedVendorToView, type Vendor } from "@/lib/vendors";
import { readSiteImages, type SiteImage } from "@/lib/siteImages";
import { trpc } from "@/lib/trpc";

const hours = [
  ["Monday", "Closed"], ["Tuesday", "Closed"], ["Wednesday", "11:00 AM–6:00 PM"],
  ["Thursday", "11:00 AM–7:00 PM"], ["Friday", "11:00 AM–7:00 PM"],
  ["Saturday", "11:00 AM–7:00 PM"], ["Sunday", "11:00 AM–6:00 PM"],
];

export default function Home() {
  const directory = trpc.directory.list.useQuery();
  const vendors = useMemo<Vendor[]>(() => { const approved = (directory.data || []).map(publishedVendorToView); const slugs = new Set(approved.map((vendor) => vendor.slug)); return [...approved, ...defaultVendors.filter((vendor) => !slugs.has(vendor.slug))]; }, [directory.data]);
  const [images] = useState<SiteImage[]>(readSiteImages);
  const heroImage = images.find((image) => image.id === "home-hero");
  const interiorImage = images.find((image) => image.id === "marketplace-interior");
  const featuredVendors = useMemo(() => vendors.filter((vendor) => vendor.active && vendor.featured).sort((a, b) => (a.displayOrder ?? 99) - (b.displayOrder ?? 99)).slice(0, 3), [vendors]);
  const structuredData = { "@context": "https://schema.org", "@type": "LocalBusiness", name: "The Cannery Marketplace", description: "A Gilroy marketplace for local makers, handcrafted goods, gift boxes, and corporate gifting.", address: { "@type": "PostalAddress", streetAddress: "7488 Monterey Road", addressLocality: "Gilroy", addressRegion: "CA", postalCode: "95020", addressCountry: "US" }, telephone: "+1-408-337-1620", url: "https://cannerymarket.com", openingHoursSpecification: [{ "@type": "OpeningHoursSpecification", dayOfWeek: "Wednesday", opens: "11:00", closes: "18:00" }, { "@type": "OpeningHoursSpecification", dayOfWeek: ["Thursday", "Friday", "Saturday"], opens: "11:00", closes: "19:00" }, { "@type": "OpeningHoursSpecification", dayOfWeek: "Sunday", opens: "11:00", closes: "18:00" }] };
  return <SiteShell><PageMeta title="Gilroy's marketplace for local makers" description="Visit The Cannery Marketplace at 7488 Monterey Road in Gilroy. Explore local makers, handcrafted goods, gifts, and community." /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} /><main>
    <section className="hero" aria-labelledby="home-title" style={{ "--hero-image": `url("${heroImage?.url}")` } as React.CSSProperties}><div className="hero-inner"><div className="hero-copy"><p className="eyebrow">Gilroy, California</p><h1 className="display" id="home-title">Made here. <em>Found by you.</em></h1><p>Discover the thoughtful, handcrafted work of the local makers who make our community one of a kind.</p><div className="hero-actions"><Link href="/vendors" className="button-primary">Meet the makers <ArrowRight size={15} /></Link><a href="#visit" className="button-secondary">Plan your visit</a></div></div><aside className="hero-card"><span className="card-kicker">Open Wednesday–Sunday</span><p>Local makers.<br />One downtown home.</p><a href="#visit"><MapPin size={14} /> Hours, map & directions</a></aside></div></section>

    <section className="home-visit-section" id="visit" aria-labelledby="visit-title"><div className="site-container home-visit-grid"><div className="home-map"><iframe title="Google Map showing The Cannery Marketplace at 7488 Monterey Road in Gilroy" src="https://maps.google.com/maps?hl=en&q=7488+Monterey+Road+Gilroy+CA+95020&z=15&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div><div className="home-visit-copy"><p className="eyebrow">Visit downtown Gilroy</p><h2 className="display" id="visit-title">Come see what your neighbors are <em>making.</em></h2><div className="visit-address"><MapPin size={19} /><div><strong>The Cannery Marketplace</strong><span>7488 Monterey Road<br />Gilroy, CA 95020</span></div></div><div className="hours-list" aria-label="Business hours"><div className="hours-heading"><Clock3 size={17} /><strong>Operating hours</strong></div>{hours.map(([day, time]) => <div className="hours-row" key={day}><span>{day}</span><strong className={time === "Closed" ? "closed" : ""}>{time}</strong></div>)}</div><a className="button-primary" href="https://maps.google.com/?q=7488+Monterey+Road+Gilroy+CA+95020" target="_blank" rel="noreferrer">Get directions <Navigation size={15} /></a></div></div></section>

    <section className="intro-section"><div className="site-container intro-grid"><div><p className="eyebrow">The Cannery Marketplace</p><h2 className="display">A home for <em>handcrafted</em> things.</h2></div><div className="intro-copy"><p className="body-large">The Cannery Marketplace in Gilroy is a dedicated space where local makers and artisans can showcase and sell their handcrafted products. We are built for the pleasure of discovering something distinctive, made close to home.</p><Link className="text-link" href="/vendors">Meet the local makers <ArrowRight size={15} /></Link></div></div></section>

    <section className="community-creed" aria-labelledby="community-title"><div className="site-container community-creed-grid"><div><p className="eyebrow">A marketplace made by its community</p><h2 className="display" id="community-title">Made here. Backed here. <em>Built to last.</em></h2></div><div className="community-creed-copy"><p className="body-large">Gilroy is shaped by makers, growers, doers, and neighbors who choose local. Every purchase keeps storefronts full, skills in motion, and opportunity close to home.</p><div className="community-values"><span>Meet the person behind the work</span><span>Choose local goods with a story</span><span>Build a stronger downtown together</span></div></div></div></section>

    {featuredVendors.length > 0 && <section className="featured-makers-section" aria-labelledby="featured-makers-title"><div className="site-container"><div className="featured-makers-heading"><div><p className="eyebrow"><Sparkles size={14} /> Fresh on the shelves</p><h2 className="display" id="featured-makers-title">Meet a few makers to <em>watch.</em></h2></div><Link className="text-link" href="/vendors">See all makers <ArrowRight size={15} /></Link></div><div className="featured-makers-grid">{featuredVendors.map((vendor) => <article className="featured-maker-card" key={vendor.slug}><Link href={`/vendors/${vendor.slug}`} className={`featured-maker-image vendor-tone-${vendor.tone}`} aria-label={`View ${vendor.name}`}><span className="placeholder-stamp">{vendor.spotlight === "popular" ? "Popular maker" : "Featured maker"}</span>{vendor.photoUrl ? <img className="vendor-photo" src={vendor.photoUrl} alt="" /> : <span className="vendor-initials">{vendor.initials}</span>}</Link><div className="featured-maker-copy"><span>{vendor.category}</span><h3><Link href={`/vendors/${vendor.slug}`}>{vendor.name}</Link></h3><p>{vendor.bio}</p></div></article>)}</div></div></section>}
    <section className="features-section" aria-label="Marketplace qualities"><div className="site-container feature-grid"><article className="feature"><span className="feature-number">01</span><h3>Local hands</h3><p>Discover work made by people in and around our community.</p></article><article className="feature"><span className="feature-number">02</span><h3>Made to keep</h3><p>Find thoughtful gifts, everyday treasures, and handcrafted pieces with a story.</p></article><article className="feature"><span className="feature-number">03</span><h3>Room to grow</h3><p>Our flexible shelf and display spaces help makers share their work in a welcoming setting.</p></article></div></section>
    <section className="image-story"><div className="site-container image-story-grid"><div className="image-frame"><img src={interiorImage?.url} alt={interiorImage?.alt} /><span className="image-caption">{interiorImage?.caption}</span></div><div className="image-story-copy"><p className="eyebrow">Shop local, naturally</p><h2 className="display">A place to <em>wander</em> awhile.</h2><p className="body-large">Stop in when you are looking for something special, or simply because you would like to see what local hands have been making.</p><Link className="text-link" href="/contact">Get in touch <ArrowRight size={15} /></Link></div></div></section>
  </main></SiteShell>;
}
