import { ArrowRight, Building2 } from "lucide-react";
import PageMeta from "@/components/PageMeta";
import SiteShell from "@/components/SiteShell";

export default function RequestQuote() {
  return (
    <SiteShell>
      <PageMeta title="Request a quote" description="Request custom pricing for corporate and bulk gift-box orders from The Cannery Marketplace." />
      <main>
        <section className="page-hero quote-hero"><div className="site-container page-hero-content"><p className="eyebrow">Corporate & bulk gifting</p><h1 className="display">A thoughtful gift, <em>at scale.</em></h1><p>Tell us what you are planning and we will work with you on quantities, packaging, timing, and custom pricing.</p></div></section>
        <section className="quote-section"><div className="site-container quote-grid"><div className="quote-intro"><div className="quote-icon"><Building2 size={22} /></div><p className="eyebrow">Let’s plan it together</p><h2 className="display">Made local. <em>Made personal.</em></h2><p className="body-large">This form is for corporate gifts, client thank-yous, event orders, and other requests that need custom pricing or invoicing. We will reply by email to discuss the details.</p><div className="quote-points"><p>Useful details to include:</p><ul><li>Estimated quantity</li><li>Preferred delivery date</li><li>Gift-box or product preferences</li><li>Shipping destinations</li></ul></div></div>
          <form className="contact-form quote-form" action="https://formsubmit.co/thecannerymarketplace@gmail.com" method="POST"><input type="hidden" name="_subject" value="New corporate gift-box quote request" /><input type="hidden" name="_template" value="table" /><input type="text" name="_honey" style={{ display: "none" }} tabIndex={-1} autoComplete="off" aria-hidden="true" /><h2>Request a quote</h2><p>We’ll use this information to start the conversation.</p><div className="form-grid"><div className="form-field"><label htmlFor="company">Company / organization *</label><input id="company" name="company" required autoComplete="organization" /></div><div className="form-field"><label htmlFor="contact-name">Your name *</label><input id="contact-name" name="name" required autoComplete="name" /></div><div className="form-field"><label htmlFor="quote-email">Email *</label><input id="quote-email" name="email" type="email" required autoComplete="email" /></div><div className="form-field"><label htmlFor="quantity">Estimated quantity</label><input id="quantity" name="quantity" inputMode="numeric" /></div><div className="form-field"><label htmlFor="date">Preferred delivery date</label><input id="date" name="delivery_date" type="date" /></div><div className="form-field"><label htmlFor="destinations">Shipping destinations</label><input id="destinations" name="destinations" placeholder="e.g. 3 California offices" /></div><div className="form-field full"><label htmlFor="quote-message">Tell us about the order *</label><textarea id="quote-message" name="message" required placeholder="What are you hoping to send? Any budget or packaging details?" /></div></div><button className="button-primary" type="submit">Send quote request <ArrowRight size={15} /></button><p className="form-note">This form requests a conversation; it does not collect payment or create an order. Please do not include confidential employee or customer information.</p></form></div></section>
      </main>
    </SiteShell>
  );
}
