import { Check, ChevronRight, ExternalLink, FileCheck2, FileSpreadsheet, Gift, LayoutDashboard, Loader2, LockKeyhole, LogOut, Settings2, Store, UserRound, UsersRound, X } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import VendorImportPanel from "@/components/VendorImportPanel";
import { trpc } from "@/lib/trpc";

const GOOGLE_FORM = "https://docs.google.com/forms/d/e/1FAIpQLSdyAfXeN1Y_vIga_U-fQWoe_Yj4eSp8pzTu4JsTkFW1exue7Q/viewform";
const tabs = [{ id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "review", label: "Review queue", icon: FileCheck2 }, { id: "vendors", label: "Published vendors", icon: UsersRound }, { id: "gifts", label: "Gift boxes", icon: Gift }, { id: "import", label: "Vendor import", icon: FileSpreadsheet }, { id: "form", label: "Google Form", icon: Settings2 }] as const;
type Tab = (typeof tabs)[number]["id"];

export default function SecureAdmin() {
  const utils = trpc.useUtils(); const session = trpc.credentials.me.useQuery(); const setup = trpc.credentials.setupStatus.useQuery();
  const [tab, setTab] = useState<Tab>("overview");
  const dashboard = trpc.adminPortal.dashboard.useQuery(undefined, { enabled: session.data?.authenticated === true && session.data.accountType === "admin" });
  const logout = trpc.credentials.logout.useMutation({ onSuccess: async () => { await session.refetch(); } });
  if (session.isLoading || setup.isLoading) return <SiteShell><main className="portal-loading"><Loader2 className="animate-spin" /> Checking secure access…</main></SiteShell>;
  if (!session.data?.authenticated || session.data.accountType !== "admin") return <AdminAccess setupRequired={setup.data?.setupRequired ?? false} onSuccess={() => session.refetch()} />;
  if (dashboard.isLoading) return <main className="portal-loading"><Loader2 className="animate-spin" /> Loading owner dashboard…</main>;
  if (dashboard.error) return <SiteShell><main className="admin-login"><div className="admin-login-card"><LockKeyhole size={24} /><h1 className="display">Dashboard unavailable</h1><p>{dashboard.error.message}</p><button className="button-plain" type="button" onClick={() => dashboard.refetch()}>Try again</button></div></main></SiteShell>;
  const data = dashboard.data!;
  const pending = data.submissions.filter((item) => item.status === "pending");
  return <div className="admin-app secure-admin-app"><aside className="admin-sidebar"><div className="admin-brand"><div className="admin-logo-mark"><Store size={19} /></div><div><strong>The Cannery</strong><span>Secure owner panel</span></div></div><div className="admin-preview-pill secure"><LockKeyhole size={12} /> Authenticated</div><nav className="admin-nav">{tabs.map((item) => { const Icon = item.icon; return <button key={item.id} className={tab === item.id ? "active" : ""} type="button" onClick={() => setTab(item.id)}><Icon size={16} /> {item.label}{item.id === "review" && pending.length > 0 && <span className="admin-count">{pending.length}</span>}</button>; })}</nav><div className="admin-sidebar-bottom"><Link href="/" target="_blank">View site <ChevronRight size={14} /></Link><button type="button" onClick={() => logout.mutate()}><LogOut size={15} /> Sign out</button></div></aside><main className="admin-main"><header className="admin-topbar"><div><p className="eyebrow">Owner dashboard</p><h1>{tabs.find((item) => item.id === tab)?.label}</h1></div><div className="admin-user"><span className="admin-avatar"><UserRound size={15} /></span><span>Marketplace owner</span></div></header>{tab === "overview" && <Overview vendorCount={data.vendors.filter((item) => item.active).length} pendingCount={pending.length} giftBoxesEnabled={data.giftBoxesEnabled} onTab={setTab} />}{tab === "review" && <ReviewQueue submissions={data.submissions} onRefresh={() => dashboard.refetch()} />}{tab === "vendors" && <PublishedVendors vendors={data.vendors} onRefresh={() => dashboard.refetch()} />}{tab === "gifts" && <GiftSetting enabled={data.giftBoxesEnabled} onRefresh={() => Promise.all([dashboard.refetch(), utils.settings.public.invalidate()])} />}{tab === "import" && <VendorImportPanel existingSlugs={data.vendors.map((item) => item.slug)} onImported={() => dashboard.refetch()} />}{tab === "form" && <GoogleFormPanel />}</main></div>;
}

function AdminAccess({ setupRequired, onSuccess }: { setupRequired: boolean; onSuccess: () => Promise<unknown> }) {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [setupToken, setSetupToken] = useState(""); const [error, setError] = useState("");
  const login = trpc.credentials.loginAdmin.useMutation({ onSuccess: async () => { setError(""); await onSuccess(); }, onError: (value) => setError(value.message) });
  const setup = trpc.credentials.setupAdmin.useMutation({ onSuccess: async () => { setError(""); await onSuccess(); }, onError: (value) => setError(value.message) });
  function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (setupRequired) setup.mutate({ setupToken, username, password }); else login.mutate({ username, password }); }
  return <SiteShell><main className="admin-login"><form className="admin-login-card" onSubmit={submit}><div className="admin-logo-mark"><LockKeyhole size={22} /></div><p className="eyebrow">Private owner area</p><h1 className="display">{setupRequired ? "Secure first-time setup." : "Owner sign in."}</h1><p>{setupRequired ? "Create the administrator username and password using the one-time setup token supplied with this handoff." : "Enter the administrator credentials. Repeated failures temporarily lock the account."}</p>{setupRequired && <label>One-time setup token<input required value={setupToken} onChange={(event) => setSetupToken(event.target.value)} autoComplete="off" /></label>}<label>Username<input required minLength={3} value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" /></label><label>Password<input required minLength={12} type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={setupRequired ? "new-password" : "current-password"} /></label>{setupRequired && <small>Use at least 12 characters with uppercase, lowercase, and a number.</small>}{error && <p className="form-error">{error}</p>}<button className="button-primary" type="submit" disabled={login.isPending || setup.isPending}>{setupRequired ? "Create administrator" : "Sign in"}</button><div className="admin-demo-note"><LockKeyhole size={15} /><span>Passwords are salted and hashed; sessions use secure HTTP-only cookies.</span></div></form></main></SiteShell>;
}

function Overview({ vendorCount, pendingCount, giftBoxesEnabled, onTab }: { vendorCount: number; pendingCount: number; giftBoxesEnabled: boolean; onTab: (tab: Tab) => void }) { return <section className="admin-content"><div className="admin-welcome"><div><p className="eyebrow">Secure content control</p><h2 className="display">Keep the marketplace <em>fresh.</em></h2><p>Vendor submissions remain private until you approve them. Public feature controls and imports are validated on the server.</p></div><div className="admin-welcome-icon"><LockKeyhole size={27} /></div></div><div className="admin-stat-grid"><button type="button" onClick={() => onTab("vendors")}><span>Published vendors</span><strong>{vendorCount}</strong><small>Manage visibility <ChevronRight size={13} /></small></button><button type="button" onClick={() => onTab("review")}><span>Pending reviews</span><strong>{pendingCount}</strong><small>Open queue <ChevronRight size={13} /></small></button><button type="button" onClick={() => onTab("gifts")}><span>Gift boxes</span><strong>{giftBoxesEnabled ? "On" : "Off"}</strong><small>Feature setting <ChevronRight size={13} /></small></button></div></section>; }

function ReviewQueue({ submissions, onRefresh }: { submissions: any[]; onRefresh: () => Promise<unknown> }) {
  const [notes, setNotes] = useState<Record<number, string>>({}); const [message, setMessage] = useState("");
  const review = trpc.adminPortal.review.useMutation({ onSuccess: async () => { setMessage("Review decision saved."); await onRefresh(); }, onError: (error) => setMessage(error.message) });
  const pending = submissions.filter((item) => item.status === "pending");
  if (!pending.length) return <section className="admin-content"><div className="admin-empty review-empty"><div className="admin-empty-icon"><Check size={19} /></div><h3>No profiles waiting</h3><p>New and updated profiles will appear here after a vendor submits them.</p></div></section>;
  return <section className="admin-content"><div className="admin-section-heading"><div><p className="eyebrow">Private until approved</p><h2>Vendor review queue</h2><p>Check names, story, authorized photos, and social links before publishing.</p></div></div>{message && <p className="admin-result">{message}</p>}<div className="secure-review-list">{pending.map((item) => <article className="secure-admin-card" key={item.id}><div className="secure-card-heading"><div><span className="review-status">Pending review</span><h3>{item.name}</h3><p>{item.category} · {item.contactEmail}</p></div>{item.coverImageUrl && <img className="secure-review-cover" src={item.coverImageUrl} alt="" />}</div><p>{item.shortBio}</p>{item.ownerBio && <div className="review-bio"><strong>About the maker</strong><p>{item.ownerBio}</p></div>}<div className="review-socials">{[["Website",item.websiteUrl],["Instagram",item.instagramUrl],["Facebook",item.facebookUrl],["TikTok",item.tiktokUrl]].filter(([,url]) => url).map(([label,url]) => <a href={url} target="_blank" rel="noreferrer" key={label}>{label} <ExternalLink size={12} /></a>)}</div>{item.galleryImageUrls?.length > 0 && <div className="review-gallery">{item.galleryImageUrls.map((url: string) => <img src={url} alt="Submitted work sample" key={url} />)}</div>}<label>Review note<textarea value={notes[item.id] || ""} onChange={(event) => setNotes({ ...notes, [item.id]: event.target.value })} placeholder="Required when requesting changes or rejecting" /></label><div className="review-actions"><button className="button-primary" type="button" onClick={() => review.mutate({ submissionId: item.id, decision: "approved", note: notes[item.id] || "" })}><Check size={14} /> Approve</button><button className="button-plain" type="button" onClick={() => review.mutate({ submissionId: item.id, decision: "changes_requested", note: notes[item.id] || "" })}><FileCheck2 size={14} /> Request changes</button><button className="danger-button" type="button" onClick={() => review.mutate({ submissionId: item.id, decision: "rejected", note: notes[item.id] || "" })}><X size={14} /> Reject</button></div></article>)}</div></section>;
}

function PublishedVendors({ vendors, onRefresh }: { vendors: any[]; onRefresh: () => Promise<unknown> }) { const toggle = trpc.adminPortal.setVendorActive.useMutation({ onSuccess: () => onRefresh() }); return <section className="admin-content"><div className="admin-section-heading"><div><p className="eyebrow">Approved public content</p><h2>Published vendors</h2><p>Deactivate a profile without deleting its approved record.</p></div></div><div className="secure-vendor-table">{vendors.length ? vendors.map((vendor) => <div key={vendor.id}><span>{vendor.coverImageUrl ? <img src={vendor.coverImageUrl} alt="" /> : vendor.name.slice(0,2).toUpperCase()}</span><div><strong>{vendor.name}</strong><small>{vendor.category} · /vendors/{vendor.slug}</small></div><label className="toggle-label"><input type="checkbox" checked={vendor.active} onChange={(event) => toggle.mutate({ id: vendor.id, active: event.target.checked })} /><span className="fake-toggle" /> {vendor.active ? "Public" : "Hidden"}</label></div>) : <div className="admin-empty"><h3>No database-backed vendors yet</h3><p>Approve a maker submission or use the one-time Excel import.</p></div>}</div></section>; }

function GiftSetting({ enabled, onRefresh }: { enabled: boolean; onRefresh: () => Promise<unknown> }) { const [message, setMessage] = useState(""); const update = trpc.adminPortal.setGiftBoxesEnabled.useMutation({ onSuccess: async () => { setMessage("Gift box setting updated."); await onRefresh(); }, onError: (error) => setMessage(error.message) }); return <section className="admin-content"><div className="admin-section-heading"><div><p className="eyebrow">Site feature control</p><h2>Gift boxes</h2><p>Turn the public gift-box catalog on or off without deleting products or checkout setup.</p></div></div><div className="secure-admin-card feature-setting-card"><div><Gift size={23} /><div><strong>Show gift boxes on the website</strong><p>When off, Gift boxes is removed from navigation and the page shows a restocking message. Corporate gifting remains available.</p></div></div><label className="toggle-label large-toggle"><input type="checkbox" checked={enabled} onChange={(event) => update.mutate({ enabled: event.target.checked })} /><span className="fake-toggle" /> {enabled ? "Enabled" : "Disabled"}</label>{message && <p className="admin-result">{message}</p>}</div></section>; }

function GoogleFormPanel() { return <section className="admin-content"><div className="admin-section-heading"><div><p className="eyebrow">Business-owned content</p><h2>Existing Google Form</h2><p>The published application remains available while the secure profile portal handles public profile submissions.</p></div><a className="button-primary" href={GOOGLE_FORM} target="_blank" rel="noreferrer">Open current form <ExternalLink size={14} /></a></div><div className="secure-admin-card google-form-card"><LockKeyhole size={22} /><div><h3>Owner-edit access requires the Google account that owns the form.</h3><p>Sign in to Google Drive with the business owner’s account, open the form, and use <strong>Share</strong> to add the owner as an <strong>Editor</strong>. Ownership transfer is only available when both accounts are in compatible Google Workspace organizations. An editor can update questions, confirmations, and settings without changing the public link.</p><p><strong>Still needed:</strong> the business owner’s Google account email and access from the current form owner. This site cannot grant Drive permissions by itself.</p></div></div></section>; }
