import { ArrowLeft, ArrowRight, ExternalLink, Facebook, Globe2, Instagram, Music2, Sparkles } from "lucide-react";
import { Link, useParams } from "wouter";
import PageMeta from "@/components/PageMeta";
import SiteShell from "@/components/SiteShell";
import { getDefaultVendor, publishedVendorToView } from "@/lib/vendors";
import { trpc } from "@/lib/trpc";

export default function VendorProfile() {
  const params = useParams<{ slug: string }>();
  const approved = trpc.directory.bySlug.useQuery({ slug: params.slug });
  const vendor = approved.data ? publishedVendorToView(approved.data) : getDefaultVendor(params.slug);
  if (approved.isLoading && !vendor) return <SiteShell><main><section className="page-hero"><div className="site-container page-hero-content"><p className="eyebrow">Loading maker</p><h1 className="display">Finding the profile…</h1></div></section></main></SiteShell>;
  if (!vendor) return <SiteShell><main><section className="page-hero"><div className="site-container page-hero-content"><p className="eyebrow">Maker not found</p><h1 className="display">That profile has moved.</h1><Link className="button-primary" href="/vendors">Back to the directory <ArrowLeft size={15} /></Link></div></section></main></SiteShell>;
  const hasStory = Boolean(vendor.ownerBio || vendor.makerStory || vendor.workSamples?.length || vendor.galleryImageUrls?.length);
  const socialLinks = [{ label: "Website", url: vendor.websiteUrl, icon: Globe2 }, { label: "Instagram", url: vendor.instagramUrl, icon: Instagram }, { label: "Facebook", url: vendor.facebookUrl, icon: Facebook }, { label: "TikTok", url: vendor.tiktokUrl, icon: Music2 }].filter((item) => item.url);
  return <SiteShell><PageMeta title={`${vendor.name} | Local maker`} description={`${vendor.name} — ${vendor.category} maker at The Cannery Marketplace in Gilroy, California. Learn the maker story and explore their work.`} /><main>
    <section className="vendor-profile-hero"><div className="site-container vendor-profile-grid"><div className={`vendor-profile-placeholder vendor-tone-${vendor.tone}`}>{vendor.photoUrl && <img className="vendor-photo" src={vendor.photoUrl} alt={`${vendor.name} profile`} />}<span className="vendor-initials">{vendor.initials}</span>{!vendor.photoUrl && <span className="placeholder-note">Maker photo coming soon</span>}</div><div className="vendor-profile-copy"><Link className="back-link" href="/vendors"><ArrowLeft size={15} /> All makers</Link><p className="eyebrow">{vendor.category}</p><h1 className="display">{vendor.name}</h1><p className="body-large">{vendor.bio}</p><div className="vendor-social-links">{socialLinks.length ? socialLinks.map(({ label, url, icon: Icon }) => <a className="button-plain" href={url} target="_blank" rel="noreferrer" key={label}><Icon size={15} /> {label} <ExternalLink size={12} /></a>) : vendor.socialUrl && <a className="button-plain" href={vendor.socialUrl} target="_blank" rel="noreferrer"><Instagram size={15} /> {vendor.socialLabel} <ExternalLink size={12} /></a>}</div></div></div></section>
    {hasStory && <><section className="maker-story-section"><div className="site-container maker-story-grid"><div><p className="eyebrow">Meet the maker</p><h2 className="display">The person behind the <em>work.</em></h2></div><div><p className="body-large">{vendor.ownerBio || vendor.makerStory}</p></div></div></section>{vendor.galleryImageUrls && vendor.galleryImageUrls.length > 0 ? <section className="maker-work-section"><div className="site-container"><div className="maker-work-heading"><div><p className="eyebrow">A closer look</p><h2 className="display">Made by <em>{vendor.name}.</em></h2></div><p>Approved photos submitted by the maker.</p></div><div className="approved-work-grid">{vendor.galleryImageUrls.map((url, index) => <figure key={url}><img src={url} alt={`${vendor.name} work sample ${index + 1}`} loading="lazy" /></figure>)}</div></div></section> : vendor.workSamples?.length ? <section className="maker-work-section"><div className="site-container"><div className="maker-work-heading"><div><p className="eyebrow">A closer look</p><h2 className="display">Made by <em>{vendor.name}.</em></h2></div><p>{vendor.makerStory}</p></div><div className="maker-work-grid">{vendor.workSamples.map((sample) => <article className={`maker-work-card maker-work-${sample.tone}`} key={sample.title}><div className="maker-work-image"><span>{sample.title}</span><small>Authorized work photo placeholder</small></div><div><h3>{sample.title}</h3><p>{sample.description}</p></div></article>)}</div></div></section> : null}</>}
    <section className="vendor-profile-bottom"><div className="site-container vendor-profile-bottom-grid"><div><p className="eyebrow">Keep exploring</p><h2 className="display">There is more to <em>find.</em></h2></div><Link className="button-primary" href="/vendors">Browse all makers <ArrowRight size={15} /></Link></div></section>
  </main></SiteShell>;
}
