import { useMemo, useRef, useState } from "react";
import { Check, Download, History, RotateCcw, Save, Upload, X } from "lucide-react";
import { readVendors, saveVendors, type Vendor } from "@/lib/vendors";

const AUDIT_KEY = "cannery-preview-vendor-audit";
type Change = { slug: string; name: string; before: Vendor | null; after: Vendor; action: "added" | "updated" };
type AuditBatch = { id: string; timestamp: string; label: string; changes: Change[] };

export function parseVendorCsv(text: string): Partial<Vendor>[] {
  const lines = text.trim().split(/\r?\n/).filter(Boolean); if (lines.length < 2) return [];
  const headers = lines[0].split(",").map((header) => header.trim().toLowerCase());
  return lines.slice(1).map((line) => { const values = line.split(",").map((value) => value.trim().replace(/^"|"$/g, "")); return Object.fromEntries(headers.map((header, index) => [header, values[index] || ""])) as Partial<Vendor>; });
}

function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
function getAudit(): AuditBatch[] { try { return JSON.parse(localStorage.getItem(AUDIT_KEY) || "[]") as AuditBatch[]; } catch { return []; } }
function saveAudit(next: AuditBatch[]) { localStorage.setItem(AUDIT_KEY, JSON.stringify(next.slice(0, 20))); }

export default function BulkVendorEditor() {
  const [vendors, setVendors] = useState<Vendor[]>(readVendors);
  const [drafts, setDrafts] = useState<Partial<Vendor>[]>([]);
  const [audit, setAudit] = useState<AuditBatch[]>(getAudit);
  const [message, setMessage] = useState("");
  const [editingCategory, setEditingCategory] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  const categories = useMemo(() => Array.from(new Set(vendors.map((vendor) => vendor.category))).sort(), [vendors]);

  function importFile(file: File) { const reader = new FileReader(); reader.onload = () => { try { const parsed = file.name.endsWith(".json") ? JSON.parse(String(reader.result)) as Partial<Vendor>[] : parseVendorCsv(String(reader.result)); setDrafts(Array.isArray(parsed) ? parsed : []); setMessage(`${Array.isArray(parsed) ? parsed.length : 0} vendor row(s) staged for review.`); } catch { setMessage("Could not read that file. Use CSV or JSON format."); } }; reader.readAsText(file); }
  function updateDraft(index: number, field: keyof Vendor, value: string | boolean) { setDrafts((current) => current.map((draft, itemIndex) => itemIndex === index ? { ...draft, [field]: value } : draft)); }
  function applyDrafts() { const changes: Change[] = []; const next = [...vendors]; drafts.forEach((draft) => { if (!draft.name && !draft.slug) return; const slug = String(draft.slug || slugify(String(draft.name))); const existing = next.find((vendor) => vendor.slug === slug) || null; const base: Vendor = existing || { slug, name: String(draft.name || slug), category: String(draft.category || "Uncategorized"), bio: "", socialLabel: "", socialUrl: "", initials: String(draft.initials || String(draft.name || "").slice(0, 2)).toUpperCase(), tone: "clay", active: true }; const after = { ...base, ...draft, slug, name: String(draft.name || base.name), category: String(draft.category || base.category), bio: String(draft.bio ?? base.bio), socialLabel: String(draft.socialLabel ?? base.socialLabel), socialUrl: String(draft.socialUrl ?? base.socialUrl), active: draft.active === undefined ? base.active : Boolean(draft.active) } as Vendor; const index = next.findIndex((vendor) => vendor.slug === slug); if (index >= 0) next[index] = after; else next.unshift(after); changes.push({ slug, name: after.name, before: existing, after, action: existing ? "updated" : "added" }); }); if (!changes.length) return; saveVendors(next); setVendors(next); const batch = { id: crypto.randomUUID(), timestamp: new Date().toISOString(), label: `Bulk update · ${changes.length} vendor(s)`, changes }; const nextAudit = [batch, ...audit]; saveAudit(nextAudit); setAudit(nextAudit); setDrafts([]); setMessage(`${changes.length} vendor change(s) applied and recorded.`); }
  function undo(batch: AuditBatch) { const current = [...vendors]; batch.changes.forEach((change) => { const index = current.findIndex((vendor) => vendor.slug === change.slug); if (change.before) { if (index >= 0) current[index] = change.before; else current.unshift(change.before); } else if (index >= 0) current.splice(index, 1); }); saveVendors(current); setVendors(current); const remaining = audit.filter((item) => item.id !== batch.id); saveAudit(remaining); setAudit(remaining); setMessage(`Undid ${batch.changes.length} change(s) from ${new Date(batch.timestamp).toLocaleString()}.`); }
  function exportVendors() { const blob = new Blob([JSON.stringify(vendors, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "cannery-vendors-backup.json"; link.click(); URL.revokeObjectURL(url); }

  return <section className="bulk-vendor-editor"><div className="bulk-vendor-heading"><div><p className="eyebrow"><History size={14} /> Bulk vendor controls</p><h3>Import once. Edit many. Undo safely.</h3><p>Import a CSV or JSON file, review the staged rows, then apply the batch. Every applied batch is saved in the local audit history.</p></div><div className="bulk-vendor-actions"><label className="upload-button"><Upload size={14} /> Import CSV/JSON<input ref={inputRef} type="file" accept=".csv,.json,text/csv,application/json" onChange={(event) => { const file = event.target.files?.[0]; if (file) importFile(file); if (inputRef.current) inputRef.current.value = ""; }} /></label><button type="button" className="button-plain" onClick={exportVendors}><Download size={14} /> Export backup</button></div></div><div className="bulk-vendor-help"><strong>Expected columns:</strong> slug, name, category, bio, socialLabel, socialUrl, initials, tone, active, featured. Existing slugs update; new slugs add records. <button type="button" onClick={() => setDrafts([{ name: "Example Maker", category: categories[0] || "Handmade Goods", bio: "", active: true }])}>Load an example row</button></div>{drafts.length > 0 && <div className="bulk-vendor-staging"><div className="bulk-vendor-staging-heading"><strong>{drafts.length} staged row(s)</strong><span>Review before applying</span><button type="button" className="icon-button" onClick={() => setDrafts([])}><X size={14} /></button></div>{drafts.map((draft, index) => <div className="bulk-vendor-row" key={`${draft.slug || draft.name}-${index}`}><input value={String(draft.name || "")} placeholder="Maker name" onChange={(event) => updateDraft(index, "name", event.target.value)} /><input value={String(draft.category || "")} placeholder="Category" onChange={(event) => updateDraft(index, "category", event.target.value)} /><input value={String(draft.bio || "")} placeholder="Short bio" onChange={(event) => updateDraft(index, "bio", event.target.value)} /><label><input type="checkbox" checked={draft.active !== false} onChange={(event) => updateDraft(index, "active", event.target.checked)} /> Active</label></div>)}<button type="button" className="button-primary" onClick={applyDrafts}><Save size={14} /> Apply staged changes</button></div>}{message && <p className="bulk-vendor-message"><Check size={14} /> {message}</p>}<div className="bulk-audit"><div className="bulk-audit-heading"><strong>Change history</strong><span>{audit.length} saved batch(es)</span></div>{audit.length === 0 ? <p>No bulk changes have been applied yet.</p> : audit.slice(0, 5).map((batch) => <div className="bulk-audit-row" key={batch.id}><span><strong>{batch.label}</strong><small>{new Date(batch.timestamp).toLocaleString()}</small></span><button type="button" className="button-plain" onClick={() => undo(batch)}><RotateCcw size={13} /> Undo batch</button></div>)}</div></section>;
}
